# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

prometheus:
  
  prometheusSpec:
    replicas: 2

    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - prometheus.tiko
